from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('master/user/', views.user_index, name='user-index'),
    path('master/user/add/', views.user_add, name='user-add'),
    path('master/user/view/<str:_id>/', views.user_view, name='user-view'),
    path('master/user/update/<str:_id>/',
         views.user_update, name='user-update'),
    path('master/user/delete/<str:_id>/',
         views.user_delete, name='user-delete'),
    path('master/user/remove-signature/<str:_id>/',
         views.remove_signature, name='remove-signature'),
    path('master/user/change-password/',
         views.change_password, name='change-password'),
    path('master/user/set-password/<str:_id>/',
         views.set_password, name='set-password'),
    path('master/position/', views.position_index, name='position-index'),
    path('master/position/add/', views.position_add, name='position-add'),
    path('master/position/view/<str:_id>/',
         views.position_view, name='position-view'),
    path('master/position/update/<str:_id>/',
         views.position_update, name='position-update'),
    path('master/position/delete/<str:_id>/',
         views.position_delete, name='position-delete'),
    path('master/menu/', views.menu_index, name='menu-index'),
    path('master/menu/add/', views.menu_add, name='menu-add'),
    path('master/menu/view/<str:_id>/', views.menu_view, name='menu-view'),
    path('master/menu/update/<str:_id>/',
         views.menu_update, name='menu-update'),
    path('master/menu/delete/<str:_id>/',
         views.menu_delete, name='menu-delete'),
    path('master/auth/update/<str:_id>/<str:_menu>/',
         views.auth_update, name='auth-update'),
    path('master/auth/delete/<str:_id>/<str:_menu>/',
         views.auth_delete, name='auth-delete'),
    path('master/closing-period/', views.closing_index, name='closing-index'),
    path('master/closing-period/add/', views.closing_add, name='closing-add'),
    path('master/closing-period/view/<str:_id>/',
         views.closing_view, name='closing-view'),
    path('master/closing-period/update/<str:_id>/', views.closing_update,
         name='closing-update'),
    path('master/closing-period/delete/<str:_id>/', views.closing_delete,
         name='closing-delete'),
    path('master/division/', views.division_index, name='division-index'),
    path('master/division/add/', views.division_add, name='division-add'),
    path('master/division/view/<str:_id>/',
         views.division_view, name='division-view'),
    path('master/division/update/<str:_id>/',
         views.division_update, name='division-update'),
    path('master/division/delete/<str:_id>/',
         views.division_delete, name='division-delete'),
    path('master/level/', views.level_index, name='level-index'),
    path('master/level/add/', views.level_add, name='level-add'),
    path('master/level/view/<str:_id>/', views.level_view, name='level-view'),
    path('master/level/update/<str:_id>/',
         views.level_update, name='level-update'),
    path('master/level/delete/<str:_id>/',
         views.level_delete, name='level-delete'),
]
