from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('master/user/', views.user_index, name='user-index'),
    path('master/user/add/', views.user_add, name='user-add'),
    path('master/user/view/<str:_id>/', views.user_view, name='user-view'),
    path('master/user/update/<str:_id>/',
         views.user_update, name='user-update'),
    path('master/user/delete/<str:_id>/',
         views.user_delete, name='user-delete'),
    path('master/user/remove-signature/<str:_id>/',
         views.remove_signature, name='remove-signature'),
    path('master/user/change-password/',
         views.change_password, name='change-password'),
    path('master/user/set-password/<str:_id>/',
         views.set_password, name='set-password'),
    path('master/position/', views.position_index, name='position-index'),
    path('master/position/add/', views.position_add, name='position-add'),
    path('master/position/view/<str:_id>/',
         views.position_view, name='position-view'),
    path('master/position/update/<str:_id>/',
         views.position_update, name='position-update'),
    path('master/position/delete/<str:_id>/',
         views.position_delete, name='position-delete'),
    path('master/menu/', views.menu_index, name='menu-index'),
    path('master/menu/add/', views.menu_add, name='menu-add'),
    path('master/menu/view/<str:_id>/', views.menu_view, name='menu-view'),
    path('master/menu/update/<str:_id>/',
         views.menu_update, name='menu-update'),
    path('master/menu/delete/<str:_id>/',
         views.menu_delete, name='menu-delete'),
    path('master/auth/update/<str:_id>/<str:_menu>/',
         views.auth_update, name='auth-update'),
    path('master/auth/delete/<str:_id>/<str:_menu>/',
         views.auth_delete, name='auth-delete'),
    path('master/closing-period/', views.closing_index, name='closing-index'),
    path('master/closing-period/add/', views.closing_add, name='closing-add'),
    path('master/closing-period/view/<str:_id>/',
         views.closing_view, name='closing-view'),
    path('master/closing-period/update/<str:_id>/', views.closing_update,
         name='closing-update'),
    path('master/closing-period/delete/<str:_id>/', views.closing_delete,
         name='closing-delete'),
    path('master/division/', views.division_index, name='division-index'),
    path('master/division/add/', views.division_add, name='division-add'),
    path('master/division/view/<str:_id>/',
         views.division_view, name='division-view'),
    path('master/division/update/<str:_id>/',
         views.division_update, name='division-update'),
    path('master/division/delete/<str:_id>/',
         views.division_delete, name='division-delete'),
    path('master/level/', views.level_index, name='level-index'),
    path('master/level/add/', views.level_add, name='level-add'),
    path('master/level/view/<str:_id>/', views.level_view, name='level-view'),
    path('master/level/update/<str:_id>/',
         views.level_update, name='level-update'),
    path('master/level/delete/<str:_id>/',
         views.level_delete, name='level-delete'),
    path('master/grade/', views.grade_index, name='grade-index'),
    path('master/grade/add/', views.grade_add, name='grade-add'),
    path('master/grade/view/<str:_id>/', views.grade_view, name='grade-view'),
    path('master/grade/update/<str:_id>/',
         views.grade_update, name='grade-update'),
    path('master/grade/delete/<str:_id>/',
         views.grade_delete, name='grade-delete'),
    path('master/religion/', views.religion_index, name='religion-index'),
    path('master/religion/add/', views.religion_add, name='religion-add'),
    path('master/religion/view/<str:_id>/',
         views.religion_view, name='religion-view'),
    path('master/religion/update/<str:_id>/',
         views.religion_update, name='religion-update'),
    path('master/religion/delete/<str:_id>/',
         views.religion_delete, name='religion-delete'),
    path('master/district/', views.district_index, name='district-index'),
    path('master/district/data/', views.district_data, name='district-data'),
    path('master/district/import/', views.district_import, name='district-import'),
    path('master/district/add/', views.district_add, name='district-add'),
    path('master/district/view/<str:_id>/',
         views.district_view, name='district-view'),
    path('master/district/update/<str:_id>/',
         views.district_update, name='district-update'),
    path('master/district/delete/<str:_id>/',
         views.district_delete, name='district-delete'),
    path('master/school-year/', views.school_year_index, name='school-year-index'),
    path('master/school-year/add/', views.school_year_add, name='school-year-add'),
    path('master/school-year/view/<str:_id>/',
         views.school_year_view, name='school-year-view'),
    path('master/school-year/update/<str:_id>/',
         views.school_year_update, name='school-year-update'),
    path('master/school-year/delete/<str:_id>/',
         views.school_year_delete, name='school-year-delete'),
    path('master/sub-district/', views.sub_district_index,
         name='sub-district-index'),
    path('master/sub-district/data/', views.sub_district_data,
         name='sub-district-data'),
    path('master/sub-district/import/', views.sub_district_import,
         name='sub-district-import'),
    path('master/sub-district/add/', views.sub_district_add,
         name='sub-district-add'),
    path('master/sub-district/view/<str:_id>/',
         views.sub_district_view, name='sub-district-view'),
    path('master/sub-district/update/<str:_id>/',
         views.sub_district_update, name='sub-district-update'),
    path('master/sub-district/delete/<str:_id>/',
         views.sub_district_delete, name='sub-district-delete'),
    path('master/village/', views.village_index, name='village-index'),
    path('master/village/data/', views.village_data, name='village-data'),
    path('master/village/import/', views.village_import, name='village-import'),
    path('master/village/add/', views.village_add, name='village-add'),
    path('master/village/view/<str:_id>/',
         views.village_view, name='village-view'),
    path('master/village/update/<str:_id>/',
         views.village_update, name='village-update'),
    path('master/village/delete/<str:_id>/',
         views.village_delete, name='village-delete'),
    path('master/hostel/', views.hostel_index, name='hostel-index'),
    path('master/hostel/add/', views.hostel_add, name='hostel-add'),
    path('master/hostel/view/<str:_id>/',
         views.hostel_view, name='hostel-view'),
    path('master/hostel/update/<str:_id>/',
         views.hostel_update, name='hostel-update'),
    path('master/hostel/delete/<str:_id>/',
         views.hostel_delete, name='hostel-delete'),
    path('master/residence-type/', views.residence_type_index,
         name='residence-type-index'),
    path('master/residence-type/add/', views.residence_type_add,
         name='residence-type-add'),
    path('master/residence-type/view/<str:_id>/',
         views.residence_type_view, name='residence-type-view'),
    path('master/residence-type/update/<str:_id>/',
         views.residence_type_update, name='residence-type-update'),
    path('master/residence-type/delete/<str:_id>/',
         views.residence_type_delete, name='residence-type-delete'),
    path('santri/', views.student_index, name='student-index'),
    path('santri/per-kelas/', views.student_by_grade, name='student-by-grade'),
    path('santri/per-kelas/<str:_id>/', views.grade_detail_view, name='grade-detail-view'),
    path('santri/per-kelas/<str:_id>/update/', views.grade_detail_update, name='grade-detail-update'),
    path('santri/per-kelas/<str:grade_id>/remove/<int:student_id>/', views.grade_remove_student, name='grade-remove-student'),
    path('santri/per-kelas/<str:grade_id>/add-student/', views.grade_add_student, name='grade-add-student'),
    path('santri/per-asrama/', views.student_by_hostel, name='student-by-hostel'),
    path('santri/per-asrama/<int:_id>/', views.hostel_detail_view, name='hostel-detail-view'),
    path('santri/per-asrama/<int:hostel_id>/add-student/', views.hostel_add_student, name='hostel-add-student'),
    path('santri/per-asrama/<int:hostel_id>/remove/<int:student_id>/', views.hostel_remove_student, name='hostel-remove-student'),
    path('santri/per-halaqoh-tahfidz/', views.student_by_halaqoh_tahfidz, name='student-by-halaqoh-tahfidz'),
    path('santri/per-halaqoh-tahfidz/<int:_id>/', views.halaqoh_tahfidz_student_view, name='halaqoh-tahfidz-student-view'),
    path('santri/per-halaqoh-tahfidz/<int:halaqoh_id>/add-student/', views.halaqoh_tahfidz_add_student, name='halaqoh-tahfidz-student-add-student'),
    path('santri/per-halaqoh-tahfidz/<int:halaqoh_id>/remove/<int:student_id>/', views.halaqoh_tahfidz_remove_student, name='halaqoh-tahfidz-student-remove-student'),
    path('santri/per-halaqoh-lughoh/', views.student_by_halaqoh_lughoh, name='student-by-halaqoh-lughoh'),
    path('santri/per-halaqoh-lughoh/<int:_id>/', views.halaqoh_lughoh_student_view, name='halaqoh-lughoh-student-view'),
    path('santri/per-halaqoh-lughoh/<int:halaqoh_id>/add-student/', views.halaqoh_lughoh_add_student, name='halaqoh-lughoh-student-add-student'),
    path('santri/per-halaqoh-lughoh/<int:halaqoh_id>/remove/<int:student_id>/', views.halaqoh_lughoh_remove_student, name='halaqoh-lughoh-student-remove-student'),
    path('santri/kelompok-belajar/', views.study_group_index, name='study-group-index'),
    path('santri/kelompok-belajar/add/', views.study_group_add, name='study-group-add'),
    path('santri/kelompok-belajar/<int:_id>/', views.study_group_detail_view, name='study-group-detail-view'),
    path('santri/kelompok-belajar/<int:_id>/update/', views.study_group_detail_update, name='study-group-detail-update'),
    path('santri/kelompok-belajar/<int:_id>/delete/', views.study_group_delete, name='study-group-delete'),
    path('santri/kelompok-belajar/<int:group_id>/add-student/', views.study_group_add_student, name='study-group-add-student'),
    path('santri/kelompok-belajar/<int:group_id>/remove/<int:student_id>/', views.study_group_remove_student, name='study-group-remove-student'),
    path('kurikulum/guru/', views.teacher_index, name='teacher-index'),
    path('kurikulum/guru/add/', views.teacher_add, name='teacher-add'),
    path('kurikulum/guru/view/<int:_id>/', views.teacher_view, name='teacher-view'),
    path('kurikulum/guru/update/<int:_id>/', views.teacher_update, name='teacher-update'),
    path('kurikulum/guru/delete/<int:_id>/', views.teacher_delete, name='teacher-delete'),
    # Halaqoh Tahfidz
    path('kurikulum/halaqoh-tahfidz/', views.halaqoh_tahfidz_index, name='halaqoh-tahfidz-index'),
    path('kurikulum/halaqoh-tahfidz/add/', views.halaqoh_tahfidz_add, name='halaqoh-tahfidz-add'),
    path('kurikulum/halaqoh-tahfidz/<int:_id>/', views.halaqoh_tahfidz_detail, name='halaqoh-tahfidz-detail'),
    path('kurikulum/halaqoh-tahfidz/<int:_id>/update/', views.halaqoh_tahfidz_update, name='halaqoh-tahfidz-update'),
    path('kurikulum/halaqoh-tahfidz/<int:_id>/delete/', views.halaqoh_tahfidz_delete, name='halaqoh-tahfidz-delete'),
    path('kurikulum/halaqoh-tahfidz/<int:halaqoh_id>/add-student/', views.halaqoh_tahfidz_add_student, name='halaqoh-tahfidz-add-student'),
    path('kurikulum/halaqoh-tahfidz/<int:halaqoh_id>/remove/<int:student_id>/', views.halaqoh_tahfidz_remove_student, name='halaqoh-tahfidz-remove-student'),
    # Halaqoh Lughoh
    path('kurikulum/halaqoh-lughoh/', views.halaqoh_lughoh_index, name='halaqoh-lughoh-index'),
    path('kurikulum/halaqoh-lughoh/add/', views.halaqoh_lughoh_add, name='halaqoh-lughoh-add'),
    path('kurikulum/halaqoh-lughoh/<int:_id>/', views.halaqoh_lughoh_detail, name='halaqoh-lughoh-detail'),
    path('kurikulum/halaqoh-lughoh/<int:_id>/update/', views.halaqoh_lughoh_update, name='halaqoh-lughoh-update'),
    path('kurikulum/halaqoh-lughoh/<int:_id>/delete/', views.halaqoh_lughoh_delete, name='halaqoh-lughoh-delete'),
    path('kurikulum/halaqoh-lughoh/<int:halaqoh_id>/add-student/', views.halaqoh_lughoh_add_student, name='halaqoh-lughoh-add-student'),
    path('kurikulum/halaqoh-lughoh/<int:halaqoh_id>/remove/<int:student_id>/', views.halaqoh_lughoh_remove_student, name='halaqoh-lughoh-remove-student'),
    # Ekstrakurikuler
    path('kurikulum/ekskul/', views.extracurricular_index, name='extracurricular-index'),
    path('kurikulum/ekskul/add/', views.extracurricular_add, name='extracurricular-add'),
    path('kurikulum/ekskul/<int:_id>/', views.extracurricular_view, name='extracurricular-view'),
    path('kurikulum/ekskul/<int:_id>/update/', views.extracurricular_update, name='extracurricular-update'),
    path('kurikulum/ekskul/<int:_id>/delete/', views.extracurricular_delete, name='extracurricular-delete'),
    # Santri Per Ekskul
    path('santri/per-ekskul/', views.student_by_extracurricular, name='student-by-extracurricular'),
    path('santri/per-ekskul/<int:_id>/', views.extracurricular_student_view, name='extracurricular-student-view'),
    path('santri/per-ekskul/<int:ekskul_id>/add-student/', views.extracurricular_add_student, name='extracurricular-add-student'),
    path('santri/per-ekskul/<int:ekskul_id>/remove/<int:student_id>/', views.extracurricular_remove_student, name='extracurricular-remove-student'),
    path('santri/add/', views.student_add, name='student-add'),
    path('santri/view/<str:_id>/', views.student_view, name='student-view'),
    path('santri/update/<str:_id>/',
         views.student_update, name='student-update'),
    path('santri/delete/<str:_id>/',
         views.student_delete, name='student-delete'),
    path('santri/ajax/sub-districts/', views.sub_district_options,
         name='sub-district-options'),
    path('santri/ajax/villages/', views.village_options,
         name='village-options'),
    path('santri/ajax/district-autocomplete/',
         views.district_autocomplete, name='district-autocomplete'),
    path('santri/ajax/sub-district-autocomplete/',
         views.sub_district_autocomplete, name='sub-district-autocomplete'),
    path('santri/ajax/village-autocomplete/',
         views.village_autocomplete, name='village-autocomplete'),
    path('santri/ajax/district-list/', views.district_list,
         name='district-list'),
    path('santri/ajax/sub-district-list/', views.sub_district_list,
         name='sub-district-list'),
    path('santri/ajax/village-list/', views.village_list,
         name='village-list'),
]
