# Generated by Django 5.0.6 on 2025-02-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promodetail',
            name='unique_promo_price',
        ),
        migrations.RenameField(
            model_name='promodetail',
            old_name='price',
            new_name='gift',
        ),
        migrations.AddConstraint(
            model_name='promodetail',
            constraint=models.UniqueConstraint(fields=('promo', 'gift'), name='unique_promo_gift'),
        ),
    ]
