# Generated by Django 5.0.6 on 2025-10-14 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_Class',
            fields=[
                ('class_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sub_grade', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
                ('school_year', models.CharField(max_length=9)),
                ('homeroom_teacher_1', models.CharField(blank=True, max_length=100, null=True)),
                ('homeroom_teacher_2', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('birth_place', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('village', models.CharField(max_length=50)),
                ('sub_district', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('rt', models.CharField(max_length=3)),
                ('rw', models.CharField(max_length=3)),
                ('postal_code', models.CharField(max_length=10)),
                ('residence_type', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('shkun_no', models.CharField(blank=True, max_length=50, null=True)),
                ('kps_recipient', models.CharField(blank=True, max_length=50, null=True)),
                ('kps_no', models.CharField(blank=True, max_length=50, null=True)),
                ('nipd', models.CharField(blank=True, max_length=50, null=True)),
                ('nisn', models.CharField(blank=True, max_length=50, null=True)),
                ('nik', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('transportation', models.CharField(blank=True, max_length=50, null=True)),
                ('handphone', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_birth_year', models.CharField(blank=True, max_length=4, null=True)),
                ('father_education', models.CharField(blank=True, max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('father_nik', models.CharField(blank=True, max_length=50, null=True)),
                ('father_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_birth_year', models.CharField(blank=True, max_length=4, null=True)),
                ('mother_education', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_nik', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_birth_year', models.CharField(blank=True, max_length=4, null=True)),
                ('guardian_education', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_nik', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_info', models.CharField(blank=True, max_length=200, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.teaching_class')),
            ],
        ),
    ]
