# Generated by Django 5.0.6 on 2024-07-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customer_customer_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasales',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
