# Generated by Django 5.0.6 on 2024-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_areasales_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasales',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areasales',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areasales',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
