# Generated by Django 5.0.6 on 2025-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_package_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promodetail',
            name='nominal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
