# Generated by Django 5.0.1 on 2024-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='areasales',
            name='bank_account',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
