# Generated by Django 5.0.6 on 2025-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_promodetail_nominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_nominal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
