# Generated by Django 5.0.6 on 2024-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_maincuisine_extra_price_sidecuisine1_extra_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackage',
            name='extra_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
