# Generated by Django 5.0.6 on 2025-02-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_order_promo_order_promo_nominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upgrade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
