# Generated by Django 5.0.6 on 2025-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_order_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='upgrade',
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='upgrade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
