# Generated by Django 5.0.6 on 2026-04-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_district_subdistrict_village_student_location_fk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subdistrict',
            name='unique_sub_district_per_district',
        ),
        migrations.RemoveConstraint(
            model_name='village',
            name='unique_village_per_sub_district',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.RemoveField(
            model_name='village',
            name='sub_district',
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='sub_district_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
