# Generated by Django 5.0.1 on 2024-03-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('package_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('box', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=10, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.category')),
            ],
        ),
        migrations.CreateModel(
            name='MainCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.CreateModel(
            name='SideCuisine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.CreateModel(
            name='SideCuisine2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.CreateModel(
            name='SideCuisine3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.CreateModel(
            name='SideCuisine4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.CreateModel(
            name='SideCuisine5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.CreateModel(
            name='SubCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cuisine')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.AddConstraint(
            model_name='maincuisine',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_main_cuisine'),
        ),
        migrations.AddConstraint(
            model_name='sidecuisine1',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_side1_cuisine'),
        ),
        migrations.AddConstraint(
            model_name='sidecuisine2',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_side2_cuisine'),
        ),
        migrations.AddConstraint(
            model_name='sidecuisine3',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_side3_cuisine'),
        ),
        migrations.AddConstraint(
            model_name='sidecuisine4',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_side4_cuisine'),
        ),
        migrations.AddConstraint(
            model_name='sidecuisine5',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_side5_cuisine'),
        ),
        migrations.AddConstraint(
            model_name='subcuisine',
            constraint=models.UniqueConstraint(fields=('package', 'cuisine'), name='unique_sub_cuisine'),
        ),
    ]
