# Generated by Django 5.0.1 on 2024-03-04 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_package_maincuisine_sidecuisine1_sidecuisine2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200, null=True)),
                ('customer_district', models.CharField(max_length=50, null=True)),
                ('customer_city', models.CharField(max_length=50, null=True)),
                ('customer_province', models.CharField(max_length=50, null=True)),
                ('customer_phone', models.CharField(max_length=50, null=True)),
                ('customer_email', models.CharField(max_length=50, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_birth', models.DateField(null=True)),
                ('child_sex', models.CharField(max_length=1, null=True)),
                ('child_father', models.CharField(max_length=200, null=True)),
                ('child_mother', models.CharField(max_length=200, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customerdetail',
            constraint=models.UniqueConstraint(fields=('customer', 'child_name'), name='unique_customer_child'),
        ),
    ]
