# Generated by Django 5.0.6 on 2025-06-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_order_upgrade_orderpackage_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('default', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackageSouvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('default', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='souvenir',
        ),
        migrations.RemoveField(
            model_name='souvenir',
            name='souvenir_id',
        ),
        migrations.RemoveField(
            model_name='souvenir',
            name='souvenir_name',
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='beverage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='box_qty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='main_cuisine_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='souvenir',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='equipment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.equipment'),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='extra_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='souvenir',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='souvenir',
            name='package',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.package'),
        ),
        migrations.AlterField(
            model_name='souvenir',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='souvenir',
            constraint=models.UniqueConstraint(fields=('package', 'equipment'), name='unique_souvenir'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.equipment'),
        ),
        migrations.AddField(
            model_name='beverage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package'),
        ),
        migrations.AddField(
            model_name='orderpackagesouvenir',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.equipment'),
        ),
        migrations.AddField(
            model_name='orderpackagesouvenir',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.order'),
        ),
        migrations.AddField(
            model_name='orderpackagesouvenir',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package'),
        ),
        migrations.AddField(
            model_name='other',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.equipment'),
        ),
        migrations.AddField(
            model_name='other',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package'),
        ),
        migrations.AddConstraint(
            model_name='beverage',
            constraint=models.UniqueConstraint(fields=('package', 'equipment'), name='unique_drink'),
        ),
        migrations.AddConstraint(
            model_name='orderpackagesouvenir',
            constraint=models.UniqueConstraint(fields=('order', 'package', 'equipment'), name='unique_order_package_souvenir'),
        ),
        migrations.AddConstraint(
            model_name='other',
            constraint=models.UniqueConstraint(fields=('package', 'equipment'), name='unique_other'),
        ),
    ]
