# Generated by Django 5.0.6 on 2026-04-30 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_subdistrict_unique_sub_district_per_district_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `apps_schoolyear` (
                        `school_year_id` bigint AUTO_INCREMENT PRIMARY KEY,
                        `school_year_name` varchar(9) NOT NULL UNIQUE,
                        `entry_date` datetime(6) NULL,
                        `entry_by` varchar(50) NULL,
                        `update_date` datetime(6) NULL,
                        `update_by` varchar(50) NULL
                    ) ENGINE=InnoDB;
                    INSERT IGNORE INTO `apps_schoolyear` (`school_year_name`)
                    SELECT DISTINCT `school_year`
                    FROM `apps_grade`
                    WHERE `school_year` IS NOT NULL AND `school_year` != '';
                    ALTER TABLE `apps_grade`
                        ADD COLUMN `school_year_tmp_id` bigint NULL;
                    UPDATE `apps_grade` AS g
                    JOIN `apps_schoolyear` AS sy
                        ON g.school_year = sy.school_year_name
                    SET g.school_year_tmp_id = sy.school_year_id
                    WHERE g.school_year IS NOT NULL AND g.school_year != '';
                    ALTER TABLE `apps_grade`
                        DROP COLUMN `school_year`;
                    ALTER TABLE `apps_grade`
                        CHANGE COLUMN `school_year_tmp_id` `school_year_id` bigint NULL;
                    ALTER TABLE `apps_grade`
                        ADD CONSTRAINT `apps_grade_school_year_id_fk`
                        FOREIGN KEY (`school_year_id`)
                        REFERENCES `apps_schoolyear` (`school_year_id`)
                        ON DELETE RESTRICT;
                    """,
                    migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='SchoolYear',
                    fields=[
                        ('school_year_id', models.BigAutoField(
                            primary_key=True, serialize=False)),
                        ('school_year_name', models.CharField(
                            max_length=9, unique=True)),
                        ('entry_date', models.DateTimeField(null=True)),
                        ('entry_by', models.CharField(max_length=50, null=True)),
                        ('update_date', models.DateTimeField(blank=True, null=True)),
                        ('update_by', models.CharField(
                            blank=True, max_length=50, null=True)),
                    ],
                ),
                migrations.AlterField(
                    model_name='grade',
                    name='school_year',
                    field=models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.schoolyear'),
                ),
            ],
        ),
    ]
