# Generated by Django 5.0.6 on 2025-07-14 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_beverage_orderpackagesouvenir_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLeftoverFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftover_food', models.CharField(max_length=50, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderleftoverfood',
            constraint=models.UniqueConstraint(fields=('order', 'package', 'leftover_food'), name='unique_order_leftover_food'),
        ),
    ]
