# Generated by Django 5.0.1 on 2024-03-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_customer_customerdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=50, null=True)),
                ('customer_email', models.CharField(max_length=50, null=True)),
                ('customer_address', models.CharField(max_length=200, null=True)),
                ('customer_district', models.CharField(max_length=50, null=True)),
                ('customer_city', models.CharField(max_length=50, null=True)),
                ('customer_province', models.CharField(max_length=50, null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('time_arrive', models.CharField(max_length=50, null=True)),
                ('total_order', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('down_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('pending_payment', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('use_foto', models.BooleanField(default=False)),
                ('witnessed', models.BooleanField(default=False)),
                ('info_source', models.CharField(max_length=50, null=True)),
                ('order_note', models.CharField(max_length=200, null=True)),
                ('cs', models.CharField(max_length=50, null=True)),
                ('order_status', models.CharField(default='PENDING', max_length=15)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=200)),
                ('child_birth', models.DateField(null=True)),
                ('child_sex', models.CharField(max_length=1, null=True)),
                ('child_father', models.CharField(max_length=200, null=True)),
                ('child_mother', models.CharField(max_length=200, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('box_type', models.CharField(max_length=50, null=True)),
                ('main_cuisine', models.CharField(max_length=50, null=True)),
                ('sub_cuisine', models.CharField(max_length=50, null=True)),
                ('side_cuisine1', models.CharField(max_length=50, null=True)),
                ('side_cuisine2', models.CharField(max_length=50, null=True)),
                ('side_cuisine3', models.CharField(max_length=50, null=True)),
                ('side_cuisine4', models.CharField(max_length=50, null=True)),
                ('side_cuisine5', models.CharField(max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.package')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderchild',
            constraint=models.UniqueConstraint(fields=('order', 'child_name'), name='unique_order_child'),
        ),
    ]
