# Generated by Django 5.0.6 on 2026-05-02 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_schoolyear_alter_grade_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.level'),
        ),
    ]
