# Generated by Django 5.0.1 on 2024-03-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_order_orderchild_orderpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seq_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
