# Generated by Django 5.0.6 on 2026-05-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_add_level_to_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_leader_of', to='apps.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_of', to='apps.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_of', to='apps.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='vice_class_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_class_leader_of', to='apps.student'),
        ),
    ]
