# Generated by Django 5.0.6 on 2026-05-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_make_student_grade_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('study_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_type_code', models.CharField(blank=True, max_length=10, null=True)),
                ('group_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(max_length=100)),
                ('group_division', models.CharField(blank=True, choices=[('1', 'Kelompok 1'), ('2', 'Kelompok 2'), ('3', 'Kelompok 3'), ('4', 'Kelompok 4'), ('5', 'Kelompok 5'), ('6', 'Kelompok 6'), ('7', 'Kelompok 7'), ('8', 'Kelompok 8'), ('9', 'Kelompok 9'), ('10', 'Kelompok 10')], max_length=2, null=True)),
                ('group_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroupMember',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_memberships', to='apps.student')),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='apps.studygroup')),
            ],
            options={
                'unique_together': {('study_group', 'student')},
            },
        ),
    ]
