# Generated by Django 5.0.1 on 2024-03-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_areasales_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpackage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.category'),
        ),
        migrations.AddConstraint(
            model_name='orderpackage',
            constraint=models.UniqueConstraint(fields=('order', 'package'), name='unique_order_package'),
        ),
    ]
