# Generated by Django 5.0.6 on 2026-05-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_add_study_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nip', models.CharField(blank=True, max_length=30, null=True, verbose_name='NIP')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Guru')),
                ('sex', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('birth_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tempat Lahir')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('status', models.CharField(blank=True, choices=[('GTY', 'Guru Tetap Yayasan'), ('GTT', 'Guru Tidak Tetap'), ('PNS', 'PNS')], max_length=3, null=True, verbose_name='Status')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mata Pelajaran')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
