# Generated by Django 5.0.1 on 2024-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_orderpackage_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('box_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('box_type_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('souvenir_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('souvenir_name', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
