# Generated by Django 5.0.6 on 2026-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_update_teacher_link_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_education',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA/SMK'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=5, null=True, verbose_name='Pendidikan Terakhir'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spesialisasi'),
        ),
    ]
