# Generated by Django 5.0.1 on 2024-03-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_boxtype_souvenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='souvenir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.souvenir'),
        ),
        migrations.AlterField(
            model_name='orderpackage',
            name='box_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.boxtype'),
        ),
    ]
