# Generated by Django 5.0.6 on 2026-05-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_teacher_replace_subject_with_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Sekolah Terakhir'),
        ),
    ]
