# Generated by Django 5.0.6 on 2026-05-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_add_last_school_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_school_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jurusan Sekolah Terakhir'),
        ),
    ]
