# Generated by Django 5.0.1 on 2024-03-20 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_rename_package_price_package_female_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.areasales'),
        ),
    ]
