# Generated by Django 5.0.4 on 2024-04-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_order_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_phone2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CashIn',
            fields=[
                ('cashin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cashin_date', models.DateTimeField(null=True)),
                ('cashin_type', models.CharField(max_length=50, null=True)),
                ('cashin_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cashin_note', models.CharField(max_length=200, null=True)),
                ('bank', models.CharField(max_length=50, null=True)),
                ('evidence', models.FileField(null=True, upload_to='cashin/')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.order')),
            ],
        ),
    ]
