# Generated by Django 5.0.6 on 2026-05-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_add_last_school_major_to_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='homeroom_teacher_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher_1_of', to='apps.teacher', verbose_name='Wali Kelas 1'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='homeroom_teacher_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher_2_of', to='apps.teacher', verbose_name='Wali Kelas 2'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Sekolah'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_school_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jurusan'),
        ),
    ]
