# Generated by Django 5.0.6 on 2026-05-04 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_study_group_teacher_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='group_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to=settings.AUTH_USER_MODEL, verbose_name='Guru Kelompok'),
        ),
    ]
