# Generated by Django 5.0.6 on 2026-05-04 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_studygroup_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='musrif',
            field=models.ForeignKey(blank=True, limit_choices_to={'position__position_name__icontains': 'musrif'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musrif_of', to=settings.AUTH_USER_MODEL, verbose_name='Musrif'),
        ),
    ]
