# Generated by Django 5.0.6 on 2026-05-04 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_add_musrif_to_hostel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalaqohLughoh',
            fields=[
                ('halaqoh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halaqoh_lughoh_set', to='apps.grade', verbose_name='Kelas')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halaqoh_lughoh_set', to='apps.teacher', verbose_name='Halaqoh (Guru)')),
            ],
        ),
        migrations.CreateModel(
            name='HalaqohTahfidz',
            fields=[
                ('halaqoh_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halaqoh_tahfidz_set', to='apps.grade', verbose_name='Kelas')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='halaqoh_tahfidz_set', to='apps.teacher', verbose_name='Halaqoh (Guru)')),
            ],
        ),
        migrations.CreateModel(
            name='HalaqohLughohMember',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('halaqoh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='apps.halaqohlughoh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaqoh_lughoh_memberships', to='apps.student')),
            ],
            options={
                'unique_together': {('halaqoh', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HalaqohTahfidzMember',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('halaqoh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='apps.halaqohtahfidz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaqoh_tahfidz_memberships', to='apps.student')),
            ],
            options={
                'unique_together': {('halaqoh', 'student')},
            },
        ),
    ]
