# Generated by Django 5.0.6 on 2026-05-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_extracurricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtracurricularMember',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('extracurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='apps.extracurricular')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracurricular_memberships', to='apps.student')),
            ],
            options={
                'unique_together': {('extracurricular', 'student')},
            },
        ),
    ]
