# Generated by Django 5.0.6 on 2026-08-27 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_subjectgroup_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('teacher_subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hours', models.PositiveIntegerField(verbose_name='Jam')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'grade', 'subject')},
            },
        ),
    ]
