# Generated by Django 5.0.6 on 2026-08-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_teachersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('grade_subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keterangan', models.CharField(blank=True, default='', max_length=100)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.subject')),
            ],
            options={
                'unique_together': {('grade', 'subject')},
            },
        ),
    ]
