# Generated by opencode

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_integrate_teachersubject_with_gradesubject'),
    ]

    operations = [
        # Room
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        # Timetable
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Terbit')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.schoolyear')),
            ],
        ),
        # Period
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu')], max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('break_name', models.CharField(blank=True, default='', max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='apps.timetable')),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('timetable', 'day', 'order')},
            },
        ),
        # Lesson
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hours_per_week', models.PositiveIntegerField(default=1)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.gradesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='apps.timetable')),
            ],
            options={
                'unique_together': {('timetable', 'grade_subject', 'teacher')},
            },
        ),
        # TimetableSlot
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('slot_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='apps.lesson')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='apps.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apps.room')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='apps.timetable')),
            ],
            options={
                'unique_together': {('timetable', 'period', 'lesson')},
            },
        ),
        # TeacherAvailability
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('availability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.period')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='apps.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_availabilities', to='apps.timetable')),
            ],
            options={
                'verbose_name_plural': 'Teacher Availabilities',
            },
        ),
        # SubstituteAssignment
        migrations.CreateModel(
            name='SubstituteAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan')], default='pending', max_length=10)),
                ('match_score', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('original_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='apps.timetableslot')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_assignments', to='apps.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='apps.timetable')),
            ],
        ),
    ]
