# Generated by Django 5.0.6 on 2026-09-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_add_schedule_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesubject',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.room'),
        ),
    ]
