# Generated by Django 5.0.6 on 2026-09-15 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_gradesubject_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='day',
            field=models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu'), ('SUN', 'Ahad')], max_length=3),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='day',
            field=models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu'), ('SUN', 'Ahad')], max_length=3),
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('availability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu'), ('SUN', 'Ahad')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.period')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='apps.room')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_availabilities', to='apps.timetable')),
            ],
            options={
                'verbose_name_plural': 'Room Availabilities',
            },
        ),
    ]
