# Generated by Django 5.0.6 on 2026-09-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_alter_period_day_alter_teacheravailability_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAvailability',
            fields=[
                ('availability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('MON', 'Senin'), ('TUE', 'Selasa'), ('WED', 'Rabu'), ('THU', 'Kamis'), ('FRI', 'Jumat'), ('SAT', 'Sabtu'), ('SUN', 'Ahad')], max_length=3)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='apps.grade')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.period')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_availabilities', to='apps.timetable')),
            ],
            options={
                'verbose_name_plural': 'Grade Availabilities',
            },
        ),
    ]
