# Generated by Django 5.0.6 on 2026-09-17 21:39

import django.db.models.deletion
from django.db import migrations, models


def seed_teacherstatus(apps, schema_editor):
    TeacherStatus = apps.get_model('apps', 'TeacherStatus')
    statuses = [
        ('GTY', 'Guru Tetap Yayasan'),
        ('GTT', 'Guru Tidak Tetap'),
        ('PNS', 'PNS'),
    ]
    for status_id, status_name in statuses:
        TeacherStatus.objects.get_or_create(
            status_id=status_id,
            defaults={'status_name': status_name}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_gradeavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStatus',
            fields=[
                ('status_id', models.CharField(help_text='Max 10 digits Status shortname.', max_length=10, primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RunPython(seed_teacherstatus, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.teacherstatus', verbose_name='Status'),
        ),
    ]
