# Generated by Django 5.0.6 on 2026-09-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_teacherstatus_alter_teacher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectgroup',
            name='group_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
