# Generated by Django 5.0.6 on 2026-09-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_alter_subjectgroup_group_code_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('1', 'Ganjil'), ('2', 'Genap')], default='1', max_length=1),
        ),
    ]
