# Generated by Django 5.0.6 on 2026-09-27 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_timetable_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('score_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1)),
                ('score1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai 1')),
                ('score2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai 2')),
                ('score3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nilai 3')),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='apps.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='apps.student')),
                ('teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_scores', to='apps.teachersubject')),
            ],
            options={
                'unique_together': {('teacher_subject', 'student', 'semester', 'school_year')},
            },
        ),
    ]
